# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHeaderView, QLCDNumber, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QTreeWidget, QTreeWidgetItem, QWidget)
from . import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1033, 721)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/icons/grid.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"QGroupBox {\n"
"        background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(255, 255, 255, 255));\n"
"        border: 1px solid gray;\n"
"        border-radius: 6px;\n"
"        border-width: 1px;\n"
"        margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QTreeWidget {\n"
"        border: 1px white;\n"
"        border-radius: 6px;\n"
"        border-width: 1px;\n"
"        margin-top: 0.5em;\n"
"}")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(11, 10, 1011, 681))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabShape(QTabWidget.TabShape.Triangular)
        self.tabWidget.setIconSize(QSize(16, 16))
        self.tabGeneral = QWidget()
        self.tabGeneral.setObjectName(u"tabGeneral")
        self.frame = QFrame(self.tabGeneral)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 1001, 641))
        self.frame.setFrameShape(QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBoxCurrentCPUTemp = QGroupBox(self.frame)
        self.groupBoxCurrentCPUTemp.setObjectName(u"groupBoxCurrentCPUTemp")
        self.groupBoxCurrentCPUTemp.setGeometry(QRect(610, 10, 181, 81))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.groupBoxCurrentCPUTemp.setFont(font1)
        self.groupBoxCurrentCPUTemp.setAutoFillBackground(False)
        self.groupBoxCurrentCPUTemp.setStyleSheet(u"")
        self.label_192 = QLabel(self.groupBoxCurrentCPUTemp)
        self.label_192.setObjectName(u"label_192")
        self.label_192.setGeometry(QRect(90, 30, 81, 41))
        font2 = QFont()
        font2.setPointSize(15)
        font2.setBold(False)
        self.label_192.setFont(font2)
        self.lcdNumberCurrentCPU = QLCDNumber(self.groupBoxCurrentCPUTemp)
        self.lcdNumberCurrentCPU.setObjectName(u"lcdNumberCurrentCPU")
        self.lcdNumberCurrentCPU.setGeometry(QRect(10, 30, 71, 41))
        font3 = QFont()
        font3.setPointSize(15)
        font3.setBold(True)
        self.lcdNumberCurrentCPU.setFont(font3)
        self.lcdNumberCurrentCPU.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberCurrentCPU.setDigitCount(3)
        self.groupBoxFanControl = QGroupBox(self.frame)
        self.groupBoxFanControl.setObjectName(u"groupBoxFanControl")
        self.groupBoxFanControl.setGeometry(QRect(10, 220, 671, 401))
        self.groupBoxFanControl.setFont(font1)
        self.radioButtonManual = QRadioButton(self.groupBoxFanControl)
        self.radioButtonManual.setObjectName(u"radioButtonManual")
        self.radioButtonManual.setGeometry(QRect(20, 30, 131, 20))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.radioButtonManual.setFont(font4)
        self.radioButtonManual.setChecked(True)
        self.radioButtonAutomatic = QRadioButton(self.groupBoxFanControl)
        self.radioButtonAutomatic.setObjectName(u"radioButtonAutomatic")
        self.radioButtonAutomatic.setEnabled(True)
        self.radioButtonAutomatic.setGeometry(QRect(20, 50, 141, 41))
        self.radioButtonAutomatic.setFont(font4)
        self.groupBoxFan1 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan1.setObjectName(u"groupBoxFan1")
        self.groupBoxFan1.setGeometry(QRect(20, 110, 301, 81))
        self.groupBoxFan1.setFont(font4)
        self.label_152 = QLabel(self.groupBoxFan1)
        self.label_152.setObjectName(u"label_152")
        self.label_152.setGeometry(QRect(260, 30, 21, 31))
        self.label_152.setFont(font)
        self.horizontalSliderFan1 = QSlider(self.groupBoxFan1)
        self.horizontalSliderFan1.setObjectName(u"horizontalSliderFan1")
        self.horizontalSliderFan1.setGeometry(QRect(10, 30, 191, 31))
        self.horizontalSliderFan1.setMaximum(100)
        self.horizontalSliderFan1.setSingleStep(1)
        self.horizontalSliderFan1.setPageStep(5)
        self.horizontalSliderFan1.setValue(0)
        self.horizontalSliderFan1.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSliderFan1.setTickPosition(QSlider.TickPosition.NoTicks)
        self.horizontalSliderFan1.setTickInterval(0)
        self.lcdNumberFan1 = QLCDNumber(self.groupBoxFan1)
        self.lcdNumberFan1.setObjectName(u"lcdNumberFan1")
        self.lcdNumberFan1.setGeometry(QRect(210, 30, 51, 31))
        font5 = QFont()
        font5.setBold(False)
        self.lcdNumberFan1.setFont(font5)
        self.lcdNumberFan1.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan1.setDigitCount(3)
        self.lcdNumberFan1.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan1.setProperty(u"intValue", 0)
        self.groupBoxFan2 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan2.setObjectName(u"groupBoxFan2")
        self.groupBoxFan2.setGeometry(QRect(20, 200, 301, 81))
        self.groupBoxFan2.setFont(font4)
        self.label_153 = QLabel(self.groupBoxFan2)
        self.label_153.setObjectName(u"label_153")
        self.label_153.setGeometry(QRect(260, 30, 21, 31))
        self.label_153.setFont(font)
        self.horizontalSliderFan2 = QSlider(self.groupBoxFan2)
        self.horizontalSliderFan2.setObjectName(u"horizontalSliderFan2")
        self.horizontalSliderFan2.setGeometry(QRect(10, 30, 191, 31))
        self.horizontalSliderFan2.setMaximum(100)
        self.horizontalSliderFan2.setSingleStep(1)
        self.horizontalSliderFan2.setPageStep(5)
        self.horizontalSliderFan2.setValue(0)
        self.horizontalSliderFan2.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumberFan2 = QLCDNumber(self.groupBoxFan2)
        self.lcdNumberFan2.setObjectName(u"lcdNumberFan2")
        self.lcdNumberFan2.setGeometry(QRect(210, 30, 51, 31))
        self.lcdNumberFan2.setFont(font5)
        self.lcdNumberFan2.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan2.setDigitCount(3)
        self.lcdNumberFan2.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan2.setProperty(u"intValue", 0)
        self.groupBoxFan3 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan3.setObjectName(u"groupBoxFan3")
        self.groupBoxFan3.setGeometry(QRect(20, 290, 301, 81))
        self.groupBoxFan3.setFont(font4)
        self.label_154 = QLabel(self.groupBoxFan3)
        self.label_154.setObjectName(u"label_154")
        self.label_154.setGeometry(QRect(260, 30, 55, 31))
        self.label_154.setFont(font)
        self.horizontalSliderFan3 = QSlider(self.groupBoxFan3)
        self.horizontalSliderFan3.setObjectName(u"horizontalSliderFan3")
        self.horizontalSliderFan3.setGeometry(QRect(10, 30, 191, 31))
        self.horizontalSliderFan3.setMaximum(100)
        self.horizontalSliderFan3.setSingleStep(1)
        self.horizontalSliderFan3.setPageStep(5)
        self.horizontalSliderFan3.setValue(0)
        self.horizontalSliderFan3.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumberFan3 = QLCDNumber(self.groupBoxFan3)
        self.lcdNumberFan3.setObjectName(u"lcdNumberFan3")
        self.lcdNumberFan3.setGeometry(QRect(210, 30, 51, 31))
        self.lcdNumberFan3.setFont(font5)
        self.lcdNumberFan3.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan3.setDigitCount(3)
        self.lcdNumberFan3.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan3.setProperty(u"intValue", 0)
        self.groupBoxFan4 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan4.setObjectName(u"groupBoxFan4")
        self.groupBoxFan4.setGeometry(QRect(350, 110, 301, 81))
        self.groupBoxFan4.setFont(font4)
        self.label_158 = QLabel(self.groupBoxFan4)
        self.label_158.setObjectName(u"label_158")
        self.label_158.setGeometry(QRect(250, 30, 55, 31))
        self.label_158.setFont(font)
        self.horizontalSliderFan4 = QSlider(self.groupBoxFan4)
        self.horizontalSliderFan4.setObjectName(u"horizontalSliderFan4")
        self.horizontalSliderFan4.setGeometry(QRect(10, 30, 181, 31))
        self.horizontalSliderFan4.setMaximum(100)
        self.horizontalSliderFan4.setSingleStep(1)
        self.horizontalSliderFan4.setPageStep(5)
        self.horizontalSliderFan4.setValue(0)
        self.horizontalSliderFan4.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumberFan4 = QLCDNumber(self.groupBoxFan4)
        self.lcdNumberFan4.setObjectName(u"lcdNumberFan4")
        self.lcdNumberFan4.setGeometry(QRect(200, 30, 51, 31))
        self.lcdNumberFan4.setFont(font5)
        self.lcdNumberFan4.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan4.setDigitCount(3)
        self.lcdNumberFan4.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan4.setProperty(u"intValue", 0)
        self.groupBoxFan6 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan6.setObjectName(u"groupBoxFan6")
        self.groupBoxFan6.setGeometry(QRect(350, 290, 301, 81))
        self.groupBoxFan6.setFont(font4)
        self.label_159 = QLabel(self.groupBoxFan6)
        self.label_159.setObjectName(u"label_159")
        self.label_159.setGeometry(QRect(250, 30, 55, 31))
        self.label_159.setFont(font)
        self.horizontalSliderFan6 = QSlider(self.groupBoxFan6)
        self.horizontalSliderFan6.setObjectName(u"horizontalSliderFan6")
        self.horizontalSliderFan6.setGeometry(QRect(10, 30, 181, 31))
        self.horizontalSliderFan6.setMaximum(100)
        self.horizontalSliderFan6.setSingleStep(1)
        self.horizontalSliderFan6.setPageStep(5)
        self.horizontalSliderFan6.setValue(0)
        self.horizontalSliderFan6.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumberFan6 = QLCDNumber(self.groupBoxFan6)
        self.lcdNumberFan6.setObjectName(u"lcdNumberFan6")
        self.lcdNumberFan6.setGeometry(QRect(200, 30, 51, 31))
        self.lcdNumberFan6.setFont(font5)
        self.lcdNumberFan6.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan6.setDigitCount(3)
        self.lcdNumberFan6.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan6.setProperty(u"intValue", 0)
        self.groupBoxFan5 = QGroupBox(self.groupBoxFanControl)
        self.groupBoxFan5.setObjectName(u"groupBoxFan5")
        self.groupBoxFan5.setGeometry(QRect(350, 200, 301, 81))
        self.groupBoxFan5.setFont(font4)
        self.label_160 = QLabel(self.groupBoxFan5)
        self.label_160.setObjectName(u"label_160")
        self.label_160.setGeometry(QRect(250, 30, 55, 31))
        self.label_160.setFont(font)
        self.horizontalSliderFan5 = QSlider(self.groupBoxFan5)
        self.horizontalSliderFan5.setObjectName(u"horizontalSliderFan5")
        self.horizontalSliderFan5.setGeometry(QRect(10, 30, 181, 31))
        self.horizontalSliderFan5.setMaximum(100)
        self.horizontalSliderFan5.setSingleStep(1)
        self.horizontalSliderFan5.setPageStep(5)
        self.horizontalSliderFan5.setValue(0)
        self.horizontalSliderFan5.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumberFan5 = QLCDNumber(self.groupBoxFan5)
        self.lcdNumberFan5.setObjectName(u"lcdNumberFan5")
        self.lcdNumberFan5.setGeometry(QRect(200, 30, 51, 31))
        self.lcdNumberFan5.setFont(font5)
        self.lcdNumberFan5.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberFan5.setDigitCount(3)
        self.lcdNumberFan5.setProperty(u"value", 0.000000000000000)
        self.lcdNumberFan5.setProperty(u"intValue", 0)
        self.groupBoxSimulateTemperatures = QGroupBox(self.groupBoxFanControl)
        self.groupBoxSimulateTemperatures.setObjectName(u"groupBoxSimulateTemperatures")
        self.groupBoxSimulateTemperatures.setEnabled(True)
        self.groupBoxSimulateTemperatures.setGeometry(QRect(350, 20, 301, 80))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(False)
        self.groupBoxSimulateTemperatures.setFont(font6)
        self.checkBoxSimulateTemp = QCheckBox(self.groupBoxSimulateTemperatures)
        self.checkBoxSimulateTemp.setObjectName(u"checkBoxSimulateTemp")
        self.checkBoxSimulateTemp.setGeometry(QRect(10, 50, 81, 21))
        font7 = QFont()
        font7.setPointSize(8)
        self.checkBoxSimulateTemp.setFont(font7)
        self.horizontalSliderCPUTemp = QSlider(self.groupBoxSimulateTemperatures)
        self.horizontalSliderCPUTemp.setObjectName(u"horizontalSliderCPUTemp")
        self.horizontalSliderCPUTemp.setGeometry(QRect(160, 20, 131, 22))
        self.horizontalSliderCPUTemp.setMaximum(100)
        self.horizontalSliderCPUTemp.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalSliderGPUTemp = QSlider(self.groupBoxSimulateTemperatures)
        self.horizontalSliderGPUTemp.setObjectName(u"horizontalSliderGPUTemp")
        self.horizontalSliderGPUTemp.setGeometry(QRect(160, 50, 131, 22))
        self.horizontalSliderGPUTemp.setMaximum(100)
        self.horizontalSliderGPUTemp.setOrientation(Qt.Orientation.Horizontal)
        self.labelCPU = QLabel(self.groupBoxSimulateTemperatures)
        self.labelCPU.setObjectName(u"labelCPU")
        self.labelCPU.setGeometry(QRect(90, 20, 61, 21))
        self.labelCPU.setFont(font7)
        self.labelGPU = QLabel(self.groupBoxSimulateTemperatures)
        self.labelGPU.setObjectName(u"labelGPU")
        self.labelGPU.setGeometry(QRect(90, 50, 61, 21))
        self.labelGPU.setFont(font7)
        self.groupBoxCurrentFanStatus = QGroupBox(self.frame)
        self.groupBoxCurrentFanStatus.setObjectName(u"groupBoxCurrentFanStatus")
        self.groupBoxCurrentFanStatus.setGeometry(QRect(700, 220, 281, 401))
        self.groupBoxCurrentFanStatus.setFont(font1)
        self.groupBoxCurrentFan1 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan1.setObjectName(u"groupBoxCurrentFan1")
        self.groupBoxCurrentFan1.setGeometry(QRect(10, 30, 261, 51))
        self.groupBoxCurrentFan1.setFont(font6)
        self.labelStatusFan1 = QLabel(self.groupBoxCurrentFan1)
        self.labelStatusFan1.setObjectName(u"labelStatusFan1")
        self.labelStatusFan1.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan1.setFont(font4)
        self.labelStatusFan1.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan1.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan1.setScaledContents(True)
        self.label_164 = QLabel(self.groupBoxCurrentFan1)
        self.label_164.setObjectName(u"label_164")
        self.label_164.setGeometry(QRect(180, 20, 41, 16))
        self.label_164.setFont(font6)
        self.labelRPMFan1 = QLabel(self.groupBoxCurrentFan1)
        self.labelRPMFan1.setObjectName(u"labelRPMFan1")
        self.labelRPMFan1.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan1.setFont(font6)
        self.label_165 = QLabel(self.groupBoxCurrentFan1)
        self.label_165.setObjectName(u"label_165")
        self.label_165.setGeometry(QRect(100, 20, 16, 16))
        self.label_165.setFont(font6)
        self.labelVFan1 = QLabel(self.groupBoxCurrentFan1)
        self.labelVFan1.setObjectName(u"labelVFan1")
        self.labelVFan1.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan1.setFont(font6)
        self.groupBoxCurrentFan2 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan2.setObjectName(u"groupBoxCurrentFan2")
        self.groupBoxCurrentFan2.setGeometry(QRect(10, 90, 261, 51))
        self.groupBoxCurrentFan2.setFont(font6)
        self.label_170 = QLabel(self.groupBoxCurrentFan2)
        self.label_170.setObjectName(u"label_170")
        self.label_170.setGeometry(QRect(180, 20, 41, 16))
        self.label_170.setFont(font6)
        self.labelRPMFan2 = QLabel(self.groupBoxCurrentFan2)
        self.labelRPMFan2.setObjectName(u"labelRPMFan2")
        self.labelRPMFan2.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan2.setFont(font6)
        self.labelStatusFan2 = QLabel(self.groupBoxCurrentFan2)
        self.labelStatusFan2.setObjectName(u"labelStatusFan2")
        self.labelStatusFan2.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan2.setFont(font4)
        self.labelStatusFan2.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan2.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan2.setScaledContents(True)
        self.labelVFan2 = QLabel(self.groupBoxCurrentFan2)
        self.labelVFan2.setObjectName(u"labelVFan2")
        self.labelVFan2.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan2.setFont(font6)
        self.label_166 = QLabel(self.groupBoxCurrentFan2)
        self.label_166.setObjectName(u"label_166")
        self.label_166.setGeometry(QRect(100, 20, 16, 16))
        self.label_166.setFont(font6)
        self.groupBoxCurrentFan3 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan3.setObjectName(u"groupBoxCurrentFan3")
        self.groupBoxCurrentFan3.setGeometry(QRect(10, 150, 261, 51))
        self.groupBoxCurrentFan3.setFont(font6)
        self.label_174 = QLabel(self.groupBoxCurrentFan3)
        self.label_174.setObjectName(u"label_174")
        self.label_174.setGeometry(QRect(180, 20, 41, 16))
        self.label_174.setFont(font6)
        self.labelRPMFan3 = QLabel(self.groupBoxCurrentFan3)
        self.labelRPMFan3.setObjectName(u"labelRPMFan3")
        self.labelRPMFan3.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan3.setFont(font6)
        self.labelStatusFan3 = QLabel(self.groupBoxCurrentFan3)
        self.labelStatusFan3.setObjectName(u"labelStatusFan3")
        self.labelStatusFan3.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan3.setFont(font4)
        self.labelStatusFan3.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan3.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan3.setScaledContents(True)
        self.labelVFan3 = QLabel(self.groupBoxCurrentFan3)
        self.labelVFan3.setObjectName(u"labelVFan3")
        self.labelVFan3.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan3.setFont(font6)
        self.label_167 = QLabel(self.groupBoxCurrentFan3)
        self.label_167.setObjectName(u"label_167")
        self.label_167.setGeometry(QRect(100, 20, 16, 16))
        self.label_167.setFont(font6)
        self.groupBoxCurrentFan4 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan4.setObjectName(u"groupBoxCurrentFan4")
        self.groupBoxCurrentFan4.setGeometry(QRect(10, 210, 261, 51))
        self.groupBoxCurrentFan4.setFont(font6)
        self.label_182 = QLabel(self.groupBoxCurrentFan4)
        self.label_182.setObjectName(u"label_182")
        self.label_182.setGeometry(QRect(180, 20, 41, 16))
        self.label_182.setFont(font6)
        self.labelRPMFan4 = QLabel(self.groupBoxCurrentFan4)
        self.labelRPMFan4.setObjectName(u"labelRPMFan4")
        self.labelRPMFan4.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan4.setFont(font6)
        self.labelStatusFan4 = QLabel(self.groupBoxCurrentFan4)
        self.labelStatusFan4.setObjectName(u"labelStatusFan4")
        self.labelStatusFan4.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan4.setFont(font4)
        self.labelStatusFan4.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan4.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan4.setScaledContents(True)
        self.labelVFan4 = QLabel(self.groupBoxCurrentFan4)
        self.labelVFan4.setObjectName(u"labelVFan4")
        self.labelVFan4.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan4.setFont(font6)
        self.label_168 = QLabel(self.groupBoxCurrentFan4)
        self.label_168.setObjectName(u"label_168")
        self.label_168.setGeometry(QRect(100, 20, 16, 16))
        self.label_168.setFont(font6)
        self.groupBoxCurrentFan5 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan5.setObjectName(u"groupBoxCurrentFan5")
        self.groupBoxCurrentFan5.setGeometry(QRect(10, 270, 261, 51))
        self.groupBoxCurrentFan5.setFont(font6)
        self.label_186 = QLabel(self.groupBoxCurrentFan5)
        self.label_186.setObjectName(u"label_186")
        self.label_186.setGeometry(QRect(180, 20, 41, 16))
        self.label_186.setFont(font6)
        self.labelRPMFan5 = QLabel(self.groupBoxCurrentFan5)
        self.labelRPMFan5.setObjectName(u"labelRPMFan5")
        self.labelRPMFan5.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan5.setFont(font6)
        self.labelStatusFan5 = QLabel(self.groupBoxCurrentFan5)
        self.labelStatusFan5.setObjectName(u"labelStatusFan5")
        self.labelStatusFan5.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan5.setFont(font4)
        self.labelStatusFan5.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan5.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan5.setScaledContents(True)
        self.labelVFan5 = QLabel(self.groupBoxCurrentFan5)
        self.labelVFan5.setObjectName(u"labelVFan5")
        self.labelVFan5.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan5.setFont(font6)
        self.label_171 = QLabel(self.groupBoxCurrentFan5)
        self.label_171.setObjectName(u"label_171")
        self.label_171.setGeometry(QRect(100, 20, 16, 16))
        self.label_171.setFont(font6)
        self.groupBoxCurrentFan6 = QGroupBox(self.groupBoxCurrentFanStatus)
        self.groupBoxCurrentFan6.setObjectName(u"groupBoxCurrentFan6")
        self.groupBoxCurrentFan6.setGeometry(QRect(10, 330, 261, 51))
        self.groupBoxCurrentFan6.setFont(font6)
        self.label_191 = QLabel(self.groupBoxCurrentFan6)
        self.label_191.setObjectName(u"label_191")
        self.label_191.setGeometry(QRect(180, 20, 41, 16))
        self.label_191.setFont(font6)
        self.labelRPMFan6 = QLabel(self.groupBoxCurrentFan6)
        self.labelRPMFan6.setObjectName(u"labelRPMFan6")
        self.labelRPMFan6.setGeometry(QRect(140, 20, 41, 16))
        self.labelRPMFan6.setFont(font6)
        self.labelStatusFan6 = QLabel(self.groupBoxCurrentFan6)
        self.labelStatusFan6.setObjectName(u"labelStatusFan6")
        self.labelStatusFan6.setGeometry(QRect(10, 20, 21, 21))
        self.labelStatusFan6.setFont(font4)
        self.labelStatusFan6.setFrameShape(QFrame.Shape.NoFrame)
        self.labelStatusFan6.setPixmap(QPixmap(u":/icons/led-red-on.png"))
        self.labelStatusFan6.setScaledContents(True)
        self.labelVFan6 = QLabel(self.groupBoxCurrentFan6)
        self.labelVFan6.setObjectName(u"labelVFan6")
        self.labelVFan6.setGeometry(QRect(60, 20, 31, 16))
        self.labelVFan6.setFont(font6)
        self.label_172 = QLabel(self.groupBoxCurrentFan6)
        self.label_172.setObjectName(u"label_172")
        self.label_172.setGeometry(QRect(100, 20, 16, 16))
        self.label_172.setFont(font6)
        self.groupBoxHWMon = QGroupBox(self.frame)
        self.groupBoxHWMon.setObjectName(u"groupBoxHWMon")
        self.groupBoxHWMon.setGeometry(QRect(330, 10, 251, 81))
        self.groupBoxHWMon.setFont(font1)
        self.label_151 = QLabel(self.groupBoxHWMon)
        self.label_151.setObjectName(u"label_151")
        self.label_151.setGeometry(QRect(20, 30, 61, 31))
        self.label_151.setFont(font4)
        self.labelHWMonStatus = QLabel(self.groupBoxHWMon)
        self.labelHWMonStatus.setObjectName(u"labelHWMonStatus")
        self.labelHWMonStatus.setGeometry(QRect(90, 30, 141, 31))
        self.labelHWMonStatus.setFont(font4)
        self.groupBoxGridSetup = QGroupBox(self.frame)
        self.groupBoxGridSetup.setObjectName(u"groupBoxGridSetup")
        self.groupBoxGridSetup.setGeometry(QRect(10, 10, 291, 201))
        self.groupBoxGridSetup.setFont(font1)
        self.label_2 = QLabel(self.groupBoxGridSetup)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 120, 31))
        self.label_2.setFont(font4)
        self.comboBoxComPorts = QComboBox(self.groupBoxGridSetup)
        self.comboBoxComPorts.addItem("")
        self.comboBoxComPorts.setObjectName(u"comboBoxComPorts")
        self.comboBoxComPorts.setGeometry(QRect(140, 30, 131, 31))
        self.comboBoxComPorts.setFont(font4)
        self.pushButtonRestart = QPushButton(self.groupBoxGridSetup)
        self.pushButtonRestart.setObjectName(u"pushButtonRestart")
        self.pushButtonRestart.setGeometry(QRect(20, 130, 251, 31))
        self.pushButtonRestart.setFont(font)
        self.label_204 = QLabel(self.groupBoxGridSetup)
        self.label_204.setObjectName(u"label_204")
        self.label_204.setGeometry(QRect(20, 80, 121, 31))
        self.label_204.setFont(font4)
        self.comboBoxPolling = QComboBox(self.groupBoxGridSetup)
        self.comboBoxPolling.addItem("")
        self.comboBoxPolling.addItem("")
        self.comboBoxPolling.addItem("")
        self.comboBoxPolling.addItem("")
        self.comboBoxPolling.addItem("")
        self.comboBoxPolling.setObjectName(u"comboBoxPolling")
        self.comboBoxPolling.setGeometry(QRect(140, 80, 71, 31))
        self.comboBoxPolling.setFont(font4)
        self.label_205 = QLabel(self.groupBoxGridSetup)
        self.label_205.setObjectName(u"label_205")
        self.label_205.setGeometry(QRect(220, 80, 41, 31))
        self.label_205.setFont(font4)
        self.groupBoxCurrentGPUTemp = QGroupBox(self.frame)
        self.groupBoxCurrentGPUTemp.setObjectName(u"groupBoxCurrentGPUTemp")
        self.groupBoxCurrentGPUTemp.setGeometry(QRect(610, 110, 181, 81))
        self.groupBoxCurrentGPUTemp.setFont(font1)
        self.label_203 = QLabel(self.groupBoxCurrentGPUTemp)
        self.label_203.setObjectName(u"label_203")
        self.label_203.setGeometry(QRect(90, 30, 81, 41))
        self.label_203.setFont(font2)
        self.lcdNumberCurrentGPU = QLCDNumber(self.groupBoxCurrentGPUTemp)
        self.lcdNumberCurrentGPU.setObjectName(u"lcdNumberCurrentGPU")
        self.lcdNumberCurrentGPU.setGeometry(QRect(10, 30, 71, 41))
        self.lcdNumberCurrentGPU.setFont(font3)
        self.lcdNumberCurrentGPU.setFrameShape(QFrame.Shape.NoFrame)
        self.lcdNumberCurrentGPU.setDigitCount(3)
        self.labelGridImage = QLabel(self.frame)
        self.labelGridImage.setObjectName(u"labelGridImage")
        self.labelGridImage.setGeometry(QRect(830, 0, 131, 121))
        self.labelGridImage.setPixmap(QPixmap(u":/icons/grid.png"))
        self.labelGridImage.setScaledContents(True)
        self.groupBoxGridSetup_2 = QGroupBox(self.frame)
        self.groupBoxGridSetup_2.setObjectName(u"groupBoxGridSetup_2")
        self.groupBoxGridSetup_2.setGeometry(QRect(330, 110, 251, 81))
        self.groupBoxGridSetup_2.setFont(font1)
        self.label_155 = QLabel(self.groupBoxGridSetup_2)
        self.label_155.setObjectName(u"label_155")
        self.label_155.setGeometry(QRect(20, 30, 101, 31))
        self.label_155.setFont(font4)
        self.labelPollingStatus = QLabel(self.groupBoxGridSetup_2)
        self.labelPollingStatus.setObjectName(u"labelPollingStatus")
        self.labelPollingStatus.setGeometry(QRect(90, 30, 121, 31))
        self.labelPollingStatus.setFont(font4)
        self.checkBoxStartMinimized = QCheckBox(self.frame)
        self.checkBoxStartMinimized.setObjectName(u"checkBoxStartMinimized")
        self.checkBoxStartMinimized.setGeometry(QRect(820, 160, 151, 20))
        self.checkBoxStartMinimized.setFont(font)
        self.checkBoxMinimizeToTray = QCheckBox(self.frame)
        self.checkBoxMinimizeToTray.setObjectName(u"checkBoxMinimizeToTray")
        self.checkBoxMinimizeToTray.setGeometry(QRect(820, 190, 151, 20))
        self.checkBoxMinimizeToTray.setFont(font)
        self.checkBoxStartSilently = QCheckBox(self.frame)
        self.checkBoxStartSilently.setObjectName(u"checkBoxStartSilently")
        self.checkBoxStartSilently.setGeometry(QRect(820, 130, 151, 20))
        self.checkBoxStartSilently.setFont(font)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabSensorConfig = QWidget()
        self.tabSensorConfig.setObjectName(u"tabSensorConfig")
        self.frame_6 = QFrame(self.tabSensorConfig)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(11, 11, 993, 641))
        self.frame_6.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_6.setLineWidth(2)
        self.pushButtonRemoveGPUSensor = QPushButton(self.frame_6)
        self.pushButtonRemoveGPUSensor.setObjectName(u"pushButtonRemoveGPUSensor")
        self.pushButtonRemoveGPUSensor.setGeometry(QRect(480, 440, 111, 28))
        self.pushButtonRemoveGPUSensor.setFont(font)
        self.groupBoxCPUSensors = QGroupBox(self.frame_6)
        self.groupBoxCPUSensors.setObjectName(u"groupBoxCPUSensors")
        self.groupBoxCPUSensors.setGeometry(QRect(620, 210, 351, 91))
        self.groupBoxCPUSensors.setFont(font)
        self.radioButtonCPUMax = QRadioButton(self.groupBoxCPUSensors)
        self.radioButtonCPUMax.setObjectName(u"radioButtonCPUMax")
        self.radioButtonCPUMax.setGeometry(QRect(11, 30, 124, 22))
        font8 = QFont()
        font8.setPointSize(9)
        self.radioButtonCPUMax.setFont(font8)
        self.radioButtonCPUMax.setChecked(True)
        self.radioButtonCPUAverage = QRadioButton(self.groupBoxCPUSensors)
        self.radioButtonCPUAverage.setObjectName(u"radioButtonCPUAverage")
        self.radioButtonCPUAverage.setGeometry(QRect(11, 52, 150, 22))
        self.radioButtonCPUAverage.setFont(font8)
        self.pushButtonAddCPUSensor = QPushButton(self.frame_6)
        self.pushButtonAddCPUSensor.setObjectName(u"pushButtonAddCPUSensor")
        self.pushButtonAddCPUSensor.setGeometry(QRect(480, 110, 111, 28))
        self.pushButtonAddCPUSensor.setFont(font)
        self.pushButtonAddGPUSensor = QPushButton(self.frame_6)
        self.pushButtonAddGPUSensor.setObjectName(u"pushButtonAddGPUSensor")
        self.pushButtonAddGPUSensor.setGeometry(QRect(480, 400, 111, 28))
        self.pushButtonAddGPUSensor.setFont(font)
        self.groupBoxGPUSensors = QGroupBox(self.frame_6)
        self.groupBoxGPUSensors.setObjectName(u"groupBoxGPUSensors")
        self.groupBoxGPUSensors.setGeometry(QRect(620, 500, 351, 81))
        self.groupBoxGPUSensors.setFont(font)
        self.radioButtonGPUMax = QRadioButton(self.groupBoxGPUSensors)
        self.radioButtonGPUMax.setObjectName(u"radioButtonGPUMax")
        self.radioButtonGPUMax.setGeometry(QRect(11, 20, 124, 31))
        self.radioButtonGPUMax.setFont(font8)
        self.radioButtonGPUMax.setChecked(True)
        self.radioButtonGPUAverage = QRadioButton(self.groupBoxGPUSensors)
        self.radioButtonGPUAverage.setObjectName(u"radioButtonGPUAverage")
        self.radioButtonGPUAverage.setGeometry(QRect(11, 50, 150, 21))
        self.radioButtonGPUAverage.setFont(font8)
        self.pushButtonRemoveCPUSensor = QPushButton(self.frame_6)
        self.pushButtonRemoveCPUSensor.setObjectName(u"pushButtonRemoveCPUSensor")
        self.pushButtonRemoveCPUSensor.setGeometry(QRect(480, 150, 111, 28))
        self.pushButtonRemoveCPUSensor.setFont(font)
        self.groupBoxAvailableSensors = QGroupBox(self.frame_6)
        self.groupBoxAvailableSensors.setObjectName(u"groupBoxAvailableSensors")
        self.groupBoxAvailableSensors.setGeometry(QRect(10, 10, 441, 611))
        self.groupBoxAvailableSensors.setFont(font4)
        self.treeWidgetHWMonData = QTreeWidget(self.groupBoxAvailableSensors)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(2, u"3");
        __qtreewidgetitem.setText(1, u"2");
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidgetHWMonData.setHeaderItem(__qtreewidgetitem)
        self.treeWidgetHWMonData.setObjectName(u"treeWidgetHWMonData")
        self.treeWidgetHWMonData.setGeometry(QRect(20, 20, 401, 571))
        self.treeWidgetHWMonData.setFont(font7)
        self.treeWidgetHWMonData.setFrameShape(QFrame.Shape.NoFrame)
        self.treeWidgetHWMonData.setColumnCount(3)
        self.treeWidgetHWMonData.header().setMinimumSectionSize(70)
        self.groupBoxSelectedCPUSensors = QGroupBox(self.frame_6)
        self.groupBoxSelectedCPUSensors.setObjectName(u"groupBoxSelectedCPUSensors")
        self.groupBoxSelectedCPUSensors.setGeometry(QRect(620, 10, 351, 191))
        self.groupBoxSelectedCPUSensors.setFont(font)
        self.treeWidgetSelectedCPUSensors = QTreeWidget(self.groupBoxSelectedCPUSensors)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(1, u"2");
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidgetSelectedCPUSensors.setHeaderItem(__qtreewidgetitem1)
        self.treeWidgetSelectedCPUSensors.setObjectName(u"treeWidgetSelectedCPUSensors")
        self.treeWidgetSelectedCPUSensors.setGeometry(QRect(20, 20, 311, 151))
        self.treeWidgetSelectedCPUSensors.setFont(font7)
        self.treeWidgetSelectedCPUSensors.setColumnCount(2)
        self.groupBoxSelectedGPUSensors = QGroupBox(self.frame_6)
        self.groupBoxSelectedGPUSensors.setObjectName(u"groupBoxSelectedGPUSensors")
        self.groupBoxSelectedGPUSensors.setGeometry(QRect(620, 330, 351, 161))
        self.groupBoxSelectedGPUSensors.setFont(font)
        self.treeWidgetSelectedGPUSensors = QTreeWidget(self.groupBoxSelectedGPUSensors)
        __qtreewidgetitem2 = QTreeWidgetItem()
        __qtreewidgetitem2.setText(1, u"2");
        __qtreewidgetitem2.setText(0, u"1");
        self.treeWidgetSelectedGPUSensors.setHeaderItem(__qtreewidgetitem2)
        self.treeWidgetSelectedGPUSensors.setObjectName(u"treeWidgetSelectedGPUSensors")
        self.treeWidgetSelectedGPUSensors.setGeometry(QRect(20, 20, 311, 121))
        self.treeWidgetSelectedGPUSensors.setFont(font7)
        self.treeWidgetSelectedGPUSensors.setColumnCount(2)
        self.label_5 = QLabel(self.frame_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(530, 600, 451, 31))
        font9 = QFont()
        font9.setPointSize(9)
        font9.setItalic(True)
        self.label_5.setFont(font9)
        self.tabWidget.addTab(self.tabSensorConfig, "")
        self.tabFanConfig = QWidget()
        self.tabFanConfig.setObjectName(u"tabFanConfig")
        self.tabFanConfig.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.groupBoxConfigFan1 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan1.setObjectName(u"groupBoxConfigFan1")
        self.groupBoxConfigFan1.setGeometry(QRect(20, 20, 471, 171))
        self.groupBoxConfigFan1.setFont(font4)
        self.groupBoxConfigFan1.setFlat(False)
        self.groupBoxConfigFan1.setCheckable(False)
        self.label_7 = QLabel(self.groupBoxConfigFan1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 30, 151, 21))
        self.label_7.setFont(font7)
        self.spinBoxMinSpeedFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxMinSpeedFan1.setObjectName(u"spinBoxMinSpeedFan1")
        self.spinBoxMinSpeedFan1.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan1.setFont(font7)
        self.spinBoxMinSpeedFan1.setMaximum(100)
        self.spinBoxMinSpeedFan1.setSingleStep(1)
        self.spinBoxMinSpeedFan1.setValue(35)
        self.label_8 = QLabel(self.groupBoxConfigFan1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 60, 241, 21))
        self.label_8.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxStartIncreaseSpeedFan1.setObjectName(u"spinBoxStartIncreaseSpeedFan1")
        self.spinBoxStartIncreaseSpeedFan1.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan1.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan1.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan1.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan1.setValue(40)
        self.label_9 = QLabel(self.groupBoxConfigFan1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(240, 90, 101, 21))
        self.label_9.setFont(font7)
        self.spinBoxIntermediateTempFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxIntermediateTempFan1.setObjectName(u"spinBoxIntermediateTempFan1")
        self.spinBoxIntermediateTempFan1.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan1.setFont(font7)
        self.spinBoxIntermediateTempFan1.setMaximum(100)
        self.spinBoxIntermediateTempFan1.setSingleStep(1)
        self.spinBoxIntermediateTempFan1.setValue(60)
        self.spinBoxIntermediateSpeedFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxIntermediateSpeedFan1.setObjectName(u"spinBoxIntermediateSpeedFan1")
        self.spinBoxIntermediateSpeedFan1.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan1.setFont(font7)
        self.spinBoxIntermediateSpeedFan1.setMaximum(100)
        self.spinBoxIntermediateSpeedFan1.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan1.setValue(60)
        self.label_11 = QLabel(self.groupBoxConfigFan1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 90, 151, 21))
        self.label_11.setFont(font7)
        self.label_10 = QLabel(self.groupBoxConfigFan1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(330, 90, 111, 21))
        self.label_10.setFont(font7)
        self.label_12 = QLabel(self.groupBoxConfigFan1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(240, 60, 111, 21))
        self.label_12.setFont(font7)
        self.label_13 = QLabel(self.groupBoxConfigFan1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 30, 111, 21))
        self.label_13.setFont(font7)
        self.label_15 = QLabel(self.groupBoxConfigFan1)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 120, 151, 21))
        self.label_15.setFont(font7)
        self.spinBoxMaxSpeedFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxMaxSpeedFan1.setObjectName(u"spinBoxMaxSpeedFan1")
        self.spinBoxMaxSpeedFan1.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan1.setFont(font7)
        self.spinBoxMaxSpeedFan1.setMaximum(100)
        self.spinBoxMaxSpeedFan1.setSingleStep(1)
        self.spinBoxMaxSpeedFan1.setValue(100)
        self.label_16 = QLabel(self.groupBoxConfigFan1)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 120, 101, 21))
        self.label_16.setFont(font7)
        self.label_17 = QLabel(self.groupBoxConfigFan1)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(330, 120, 111, 21))
        self.label_17.setFont(font7)
        self.spinBoxMaxTempFan1 = QSpinBox(self.groupBoxConfigFan1)
        self.spinBoxMaxTempFan1.setObjectName(u"spinBoxMaxTempFan1")
        self.spinBoxMaxTempFan1.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan1.setFont(font7)
        self.spinBoxMaxTempFan1.setMaximum(100)
        self.spinBoxMaxTempFan1.setSingleStep(1)
        self.spinBoxMaxTempFan1.setValue(75)
        self.radioButtonCPUFan1 = QRadioButton(self.groupBoxConfigFan1)
        self.radioButtonCPUFan1.setObjectName(u"radioButtonCPUFan1")
        self.radioButtonCPUFan1.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan1.setFont(font7)
        self.radioButtonCPUFan1.setChecked(True)
        self.radioButtonGPUFan1 = QRadioButton(self.groupBoxConfigFan1)
        self.radioButtonGPUFan1.setObjectName(u"radioButtonGPUFan1")
        self.radioButtonGPUFan1.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan1.setFont(font7)
        self.groupBoxConfigFan2 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan2.setObjectName(u"groupBoxConfigFan2")
        self.groupBoxConfigFan2.setGeometry(QRect(20, 210, 471, 171))
        self.groupBoxConfigFan2.setFont(font4)
        self.groupBoxConfigFan2.setFlat(False)
        self.groupBoxConfigFan2.setCheckable(False)
        self.label_27 = QLabel(self.groupBoxConfigFan2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 30, 151, 21))
        self.label_27.setFont(font7)
        self.spinBoxMinSpeedFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxMinSpeedFan2.setObjectName(u"spinBoxMinSpeedFan2")
        self.spinBoxMinSpeedFan2.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan2.setFont(font7)
        self.spinBoxMinSpeedFan2.setMaximum(100)
        self.spinBoxMinSpeedFan2.setSingleStep(1)
        self.spinBoxMinSpeedFan2.setValue(35)
        self.label_28 = QLabel(self.groupBoxConfigFan2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 60, 241, 21))
        self.label_28.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxStartIncreaseSpeedFan2.setObjectName(u"spinBoxStartIncreaseSpeedFan2")
        self.spinBoxStartIncreaseSpeedFan2.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan2.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan2.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan2.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan2.setValue(40)
        self.label_29 = QLabel(self.groupBoxConfigFan2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 90, 101, 21))
        self.label_29.setFont(font7)
        self.spinBoxIntermediateTempFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxIntermediateTempFan2.setObjectName(u"spinBoxIntermediateTempFan2")
        self.spinBoxIntermediateTempFan2.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan2.setFont(font7)
        self.spinBoxIntermediateTempFan2.setMaximum(100)
        self.spinBoxIntermediateTempFan2.setSingleStep(1)
        self.spinBoxIntermediateTempFan2.setValue(60)
        self.spinBoxIntermediateSpeedFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxIntermediateSpeedFan2.setObjectName(u"spinBoxIntermediateSpeedFan2")
        self.spinBoxIntermediateSpeedFan2.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan2.setFont(font7)
        self.spinBoxIntermediateSpeedFan2.setMaximum(100)
        self.spinBoxIntermediateSpeedFan2.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan2.setValue(60)
        self.label_30 = QLabel(self.groupBoxConfigFan2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 90, 151, 21))
        self.label_30.setFont(font7)
        self.label_31 = QLabel(self.groupBoxConfigFan2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(330, 90, 111, 21))
        self.label_31.setFont(font7)
        self.label_32 = QLabel(self.groupBoxConfigFan2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(240, 60, 111, 21))
        self.label_32.setFont(font7)
        self.label_33 = QLabel(self.groupBoxConfigFan2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(240, 30, 111, 21))
        self.label_33.setFont(font7)
        self.label_34 = QLabel(self.groupBoxConfigFan2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 120, 151, 21))
        self.label_34.setFont(font7)
        self.spinBoxMaxSpeedFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxMaxSpeedFan2.setObjectName(u"spinBoxMaxSpeedFan2")
        self.spinBoxMaxSpeedFan2.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan2.setFont(font7)
        self.spinBoxMaxSpeedFan2.setMaximum(100)
        self.spinBoxMaxSpeedFan2.setSingleStep(1)
        self.spinBoxMaxSpeedFan2.setValue(100)
        self.label_35 = QLabel(self.groupBoxConfigFan2)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(240, 120, 101, 21))
        self.label_35.setFont(font7)
        self.label_36 = QLabel(self.groupBoxConfigFan2)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(330, 120, 111, 21))
        self.label_36.setFont(font7)
        self.spinBoxMaxTempFan2 = QSpinBox(self.groupBoxConfigFan2)
        self.spinBoxMaxTempFan2.setObjectName(u"spinBoxMaxTempFan2")
        self.spinBoxMaxTempFan2.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan2.setFont(font7)
        self.spinBoxMaxTempFan2.setMaximum(100)
        self.spinBoxMaxTempFan2.setSingleStep(1)
        self.spinBoxMaxTempFan2.setValue(75)
        self.radioButtonCPUFan2 = QRadioButton(self.groupBoxConfigFan2)
        self.radioButtonCPUFan2.setObjectName(u"radioButtonCPUFan2")
        self.radioButtonCPUFan2.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan2.setFont(font7)
        self.radioButtonCPUFan2.setChecked(True)
        self.radioButtonGPUFan2 = QRadioButton(self.groupBoxConfigFan2)
        self.radioButtonGPUFan2.setObjectName(u"radioButtonGPUFan2")
        self.radioButtonGPUFan2.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan2.setFont(font7)
        self.groupBoxConfigFan3 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan3.setObjectName(u"groupBoxConfigFan3")
        self.groupBoxConfigFan3.setGeometry(QRect(20, 400, 471, 171))
        self.groupBoxConfigFan3.setFont(font4)
        self.groupBoxConfigFan3.setFlat(False)
        self.groupBoxConfigFan3.setCheckable(False)
        self.label_37 = QLabel(self.groupBoxConfigFan3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 30, 151, 21))
        self.label_37.setFont(font7)
        self.spinBoxMinSpeedFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxMinSpeedFan3.setObjectName(u"spinBoxMinSpeedFan3")
        self.spinBoxMinSpeedFan3.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan3.setFont(font7)
        self.spinBoxMinSpeedFan3.setMaximum(100)
        self.spinBoxMinSpeedFan3.setSingleStep(1)
        self.spinBoxMinSpeedFan3.setValue(35)
        self.label_38 = QLabel(self.groupBoxConfigFan3)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(20, 60, 241, 21))
        self.label_38.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxStartIncreaseSpeedFan3.setObjectName(u"spinBoxStartIncreaseSpeedFan3")
        self.spinBoxStartIncreaseSpeedFan3.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan3.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan3.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan3.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan3.setValue(40)
        self.label_39 = QLabel(self.groupBoxConfigFan3)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(240, 90, 101, 21))
        self.label_39.setFont(font7)
        self.spinBoxIntermediateTempFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxIntermediateTempFan3.setObjectName(u"spinBoxIntermediateTempFan3")
        self.spinBoxIntermediateTempFan3.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan3.setFont(font7)
        self.spinBoxIntermediateTempFan3.setMaximum(100)
        self.spinBoxIntermediateTempFan3.setSingleStep(1)
        self.spinBoxIntermediateTempFan3.setValue(60)
        self.spinBoxIntermediateSpeedFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxIntermediateSpeedFan3.setObjectName(u"spinBoxIntermediateSpeedFan3")
        self.spinBoxIntermediateSpeedFan3.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan3.setFont(font7)
        self.spinBoxIntermediateSpeedFan3.setMaximum(100)
        self.spinBoxIntermediateSpeedFan3.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan3.setValue(60)
        self.label_40 = QLabel(self.groupBoxConfigFan3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 90, 151, 21))
        self.label_40.setFont(font7)
        self.label_41 = QLabel(self.groupBoxConfigFan3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(330, 90, 111, 21))
        self.label_41.setFont(font7)
        self.label_42 = QLabel(self.groupBoxConfigFan3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(240, 60, 111, 21))
        self.label_42.setFont(font7)
        self.label_43 = QLabel(self.groupBoxConfigFan3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 30, 111, 21))
        self.label_43.setFont(font7)
        self.label_44 = QLabel(self.groupBoxConfigFan3)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 120, 151, 21))
        self.label_44.setFont(font7)
        self.spinBoxMaxSpeedFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxMaxSpeedFan3.setObjectName(u"spinBoxMaxSpeedFan3")
        self.spinBoxMaxSpeedFan3.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan3.setFont(font7)
        self.spinBoxMaxSpeedFan3.setMaximum(100)
        self.spinBoxMaxSpeedFan3.setSingleStep(1)
        self.spinBoxMaxSpeedFan3.setValue(100)
        self.label_45 = QLabel(self.groupBoxConfigFan3)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(240, 120, 101, 21))
        self.label_45.setFont(font7)
        self.label_46 = QLabel(self.groupBoxConfigFan3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(330, 120, 111, 21))
        self.label_46.setFont(font7)
        self.spinBoxMaxTempFan3 = QSpinBox(self.groupBoxConfigFan3)
        self.spinBoxMaxTempFan3.setObjectName(u"spinBoxMaxTempFan3")
        self.spinBoxMaxTempFan3.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan3.setFont(font7)
        self.spinBoxMaxTempFan3.setMaximum(100)
        self.spinBoxMaxTempFan3.setSingleStep(1)
        self.spinBoxMaxTempFan3.setValue(75)
        self.radioButtonCPUFan3 = QRadioButton(self.groupBoxConfigFan3)
        self.radioButtonCPUFan3.setObjectName(u"radioButtonCPUFan3")
        self.radioButtonCPUFan3.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan3.setFont(font7)
        self.radioButtonCPUFan3.setChecked(True)
        self.radioButtonGPUFan3 = QRadioButton(self.groupBoxConfigFan3)
        self.radioButtonGPUFan3.setObjectName(u"radioButtonGPUFan3")
        self.radioButtonGPUFan3.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan3.setFont(font7)
        self.groupBoxConfigFan4 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan4.setObjectName(u"groupBoxConfigFan4")
        self.groupBoxConfigFan4.setGeometry(QRect(510, 20, 471, 171))
        self.groupBoxConfigFan4.setFont(font4)
        self.groupBoxConfigFan4.setFlat(False)
        self.groupBoxConfigFan4.setCheckable(False)
        self.label_47 = QLabel(self.groupBoxConfigFan4)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(20, 30, 151, 21))
        self.label_47.setFont(font7)
        self.spinBoxMinSpeedFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxMinSpeedFan4.setObjectName(u"spinBoxMinSpeedFan4")
        self.spinBoxMinSpeedFan4.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan4.setFont(font7)
        self.spinBoxMinSpeedFan4.setMaximum(100)
        self.spinBoxMinSpeedFan4.setSingleStep(1)
        self.spinBoxMinSpeedFan4.setValue(35)
        self.label_48 = QLabel(self.groupBoxConfigFan4)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, 60, 241, 21))
        self.label_48.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxStartIncreaseSpeedFan4.setObjectName(u"spinBoxStartIncreaseSpeedFan4")
        self.spinBoxStartIncreaseSpeedFan4.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan4.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan4.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan4.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan4.setValue(40)
        self.label_49 = QLabel(self.groupBoxConfigFan4)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(240, 90, 101, 21))
        self.label_49.setFont(font7)
        self.spinBoxIntermediateTempFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxIntermediateTempFan4.setObjectName(u"spinBoxIntermediateTempFan4")
        self.spinBoxIntermediateTempFan4.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan4.setFont(font7)
        self.spinBoxIntermediateTempFan4.setMaximum(100)
        self.spinBoxIntermediateTempFan4.setSingleStep(1)
        self.spinBoxIntermediateTempFan4.setValue(60)
        self.spinBoxIntermediateSpeedFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxIntermediateSpeedFan4.setObjectName(u"spinBoxIntermediateSpeedFan4")
        self.spinBoxIntermediateSpeedFan4.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan4.setFont(font7)
        self.spinBoxIntermediateSpeedFan4.setMaximum(100)
        self.spinBoxIntermediateSpeedFan4.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan4.setValue(60)
        self.label_50 = QLabel(self.groupBoxConfigFan4)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(20, 90, 151, 21))
        self.label_50.setFont(font7)
        self.label_51 = QLabel(self.groupBoxConfigFan4)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(330, 90, 111, 21))
        self.label_51.setFont(font7)
        self.label_52 = QLabel(self.groupBoxConfigFan4)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(240, 60, 111, 21))
        self.label_52.setFont(font7)
        self.label_53 = QLabel(self.groupBoxConfigFan4)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(240, 30, 111, 21))
        self.label_53.setFont(font7)
        self.label_54 = QLabel(self.groupBoxConfigFan4)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(20, 120, 151, 21))
        self.label_54.setFont(font7)
        self.spinBoxMaxSpeedFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxMaxSpeedFan4.setObjectName(u"spinBoxMaxSpeedFan4")
        self.spinBoxMaxSpeedFan4.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan4.setFont(font7)
        self.spinBoxMaxSpeedFan4.setMaximum(100)
        self.spinBoxMaxSpeedFan4.setSingleStep(1)
        self.spinBoxMaxSpeedFan4.setValue(100)
        self.label_55 = QLabel(self.groupBoxConfigFan4)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(240, 120, 101, 21))
        self.label_55.setFont(font7)
        self.label_56 = QLabel(self.groupBoxConfigFan4)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(330, 120, 111, 21))
        self.label_56.setFont(font7)
        self.spinBoxMaxTempFan4 = QSpinBox(self.groupBoxConfigFan4)
        self.spinBoxMaxTempFan4.setObjectName(u"spinBoxMaxTempFan4")
        self.spinBoxMaxTempFan4.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan4.setFont(font7)
        self.spinBoxMaxTempFan4.setMaximum(100)
        self.spinBoxMaxTempFan4.setSingleStep(1)
        self.spinBoxMaxTempFan4.setValue(75)
        self.radioButtonCPUFan4 = QRadioButton(self.groupBoxConfigFan4)
        self.radioButtonCPUFan4.setObjectName(u"radioButtonCPUFan4")
        self.radioButtonCPUFan4.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan4.setFont(font7)
        self.radioButtonCPUFan4.setChecked(True)
        self.radioButtonGPUFan4 = QRadioButton(self.groupBoxConfigFan4)
        self.radioButtonGPUFan4.setObjectName(u"radioButtonGPUFan4")
        self.radioButtonGPUFan4.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan4.setFont(font7)
        self.groupBoxConfigFan5 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan5.setObjectName(u"groupBoxConfigFan5")
        self.groupBoxConfigFan5.setGeometry(QRect(510, 210, 471, 171))
        self.groupBoxConfigFan5.setFont(font4)
        self.groupBoxConfigFan5.setFlat(False)
        self.groupBoxConfigFan5.setCheckable(False)
        self.label_57 = QLabel(self.groupBoxConfigFan5)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 30, 151, 21))
        self.label_57.setFont(font7)
        self.spinBoxMinSpeedFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxMinSpeedFan5.setObjectName(u"spinBoxMinSpeedFan5")
        self.spinBoxMinSpeedFan5.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan5.setFont(font7)
        self.spinBoxMinSpeedFan5.setMaximum(100)
        self.spinBoxMinSpeedFan5.setSingleStep(1)
        self.spinBoxMinSpeedFan5.setValue(35)
        self.label_58 = QLabel(self.groupBoxConfigFan5)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 60, 241, 21))
        self.label_58.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxStartIncreaseSpeedFan5.setObjectName(u"spinBoxStartIncreaseSpeedFan5")
        self.spinBoxStartIncreaseSpeedFan5.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan5.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan5.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan5.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan5.setValue(40)
        self.label_59 = QLabel(self.groupBoxConfigFan5)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(240, 90, 101, 21))
        self.label_59.setFont(font7)
        self.spinBoxIntermediateTempFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxIntermediateTempFan5.setObjectName(u"spinBoxIntermediateTempFan5")
        self.spinBoxIntermediateTempFan5.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan5.setFont(font7)
        self.spinBoxIntermediateTempFan5.setMaximum(100)
        self.spinBoxIntermediateTempFan5.setSingleStep(1)
        self.spinBoxIntermediateTempFan5.setValue(60)
        self.spinBoxIntermediateSpeedFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxIntermediateSpeedFan5.setObjectName(u"spinBoxIntermediateSpeedFan5")
        self.spinBoxIntermediateSpeedFan5.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan5.setFont(font7)
        self.spinBoxIntermediateSpeedFan5.setMaximum(100)
        self.spinBoxIntermediateSpeedFan5.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan5.setValue(60)
        self.label_60 = QLabel(self.groupBoxConfigFan5)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(20, 90, 151, 21))
        self.label_60.setFont(font7)
        self.label_61 = QLabel(self.groupBoxConfigFan5)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(330, 90, 111, 21))
        self.label_61.setFont(font7)
        self.label_62 = QLabel(self.groupBoxConfigFan5)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(240, 60, 111, 21))
        self.label_62.setFont(font7)
        self.label_63 = QLabel(self.groupBoxConfigFan5)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(240, 30, 111, 21))
        self.label_63.setFont(font7)
        self.label_64 = QLabel(self.groupBoxConfigFan5)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(20, 120, 151, 21))
        self.label_64.setFont(font7)
        self.spinBoxMaxSpeedFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxMaxSpeedFan5.setObjectName(u"spinBoxMaxSpeedFan5")
        self.spinBoxMaxSpeedFan5.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan5.setFont(font7)
        self.spinBoxMaxSpeedFan5.setMaximum(100)
        self.spinBoxMaxSpeedFan5.setSingleStep(1)
        self.spinBoxMaxSpeedFan5.setValue(100)
        self.label_65 = QLabel(self.groupBoxConfigFan5)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(240, 120, 101, 21))
        self.label_65.setFont(font7)
        self.label_66 = QLabel(self.groupBoxConfigFan5)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(330, 120, 111, 21))
        self.label_66.setFont(font7)
        self.spinBoxMaxTempFan5 = QSpinBox(self.groupBoxConfigFan5)
        self.spinBoxMaxTempFan5.setObjectName(u"spinBoxMaxTempFan5")
        self.spinBoxMaxTempFan5.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan5.setFont(font7)
        self.spinBoxMaxTempFan5.setMaximum(100)
        self.spinBoxMaxTempFan5.setSingleStep(1)
        self.spinBoxMaxTempFan5.setValue(75)
        self.radioButtonCPUFan5 = QRadioButton(self.groupBoxConfigFan5)
        self.radioButtonCPUFan5.setObjectName(u"radioButtonCPUFan5")
        self.radioButtonCPUFan5.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan5.setFont(font7)
        self.radioButtonCPUFan5.setChecked(True)
        self.radioButtonGPUFan5 = QRadioButton(self.groupBoxConfigFan5)
        self.radioButtonGPUFan5.setObjectName(u"radioButtonGPUFan5")
        self.radioButtonGPUFan5.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan5.setFont(font7)
        self.groupBoxConfigFan6 = QGroupBox(self.tabFanConfig)
        self.groupBoxConfigFan6.setObjectName(u"groupBoxConfigFan6")
        self.groupBoxConfigFan6.setGeometry(QRect(510, 400, 471, 171))
        self.groupBoxConfigFan6.setFont(font4)
        self.groupBoxConfigFan6.setFlat(False)
        self.groupBoxConfigFan6.setCheckable(False)
        self.label_67 = QLabel(self.groupBoxConfigFan6)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 30, 151, 21))
        self.label_67.setFont(font7)
        self.spinBoxMinSpeedFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxMinSpeedFan6.setObjectName(u"spinBoxMinSpeedFan6")
        self.spinBoxMinSpeedFan6.setGeometry(QRect(190, 30, 42, 21))
        self.spinBoxMinSpeedFan6.setFont(font7)
        self.spinBoxMinSpeedFan6.setMaximum(100)
        self.spinBoxMinSpeedFan6.setSingleStep(1)
        self.spinBoxMinSpeedFan6.setValue(35)
        self.label_68 = QLabel(self.groupBoxConfigFan6)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(20, 60, 241, 21))
        self.label_68.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxStartIncreaseSpeedFan6.setObjectName(u"spinBoxStartIncreaseSpeedFan6")
        self.spinBoxStartIncreaseSpeedFan6.setGeometry(QRect(190, 60, 42, 21))
        self.spinBoxStartIncreaseSpeedFan6.setFont(font7)
        self.spinBoxStartIncreaseSpeedFan6.setMaximum(100)
        self.spinBoxStartIncreaseSpeedFan6.setSingleStep(1)
        self.spinBoxStartIncreaseSpeedFan6.setValue(40)
        self.label_69 = QLabel(self.groupBoxConfigFan6)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(240, 90, 101, 21))
        self.label_69.setFont(font7)
        self.spinBoxIntermediateTempFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxIntermediateTempFan6.setObjectName(u"spinBoxIntermediateTempFan6")
        self.spinBoxIntermediateTempFan6.setGeometry(QRect(280, 90, 42, 21))
        self.spinBoxIntermediateTempFan6.setFont(font7)
        self.spinBoxIntermediateTempFan6.setMaximum(100)
        self.spinBoxIntermediateTempFan6.setSingleStep(1)
        self.spinBoxIntermediateTempFan6.setValue(60)
        self.spinBoxIntermediateSpeedFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxIntermediateSpeedFan6.setObjectName(u"spinBoxIntermediateSpeedFan6")
        self.spinBoxIntermediateSpeedFan6.setGeometry(QRect(190, 90, 42, 21))
        self.spinBoxIntermediateSpeedFan6.setFont(font7)
        self.spinBoxIntermediateSpeedFan6.setMaximum(100)
        self.spinBoxIntermediateSpeedFan6.setSingleStep(1)
        self.spinBoxIntermediateSpeedFan6.setValue(60)
        self.label_70 = QLabel(self.groupBoxConfigFan6)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(20, 90, 151, 21))
        self.label_70.setFont(font7)
        self.label_71 = QLabel(self.groupBoxConfigFan6)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(330, 90, 111, 21))
        self.label_71.setFont(font7)
        self.label_72 = QLabel(self.groupBoxConfigFan6)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(240, 60, 111, 21))
        self.label_72.setFont(font7)
        self.label_73 = QLabel(self.groupBoxConfigFan6)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(240, 30, 111, 21))
        self.label_73.setFont(font7)
        self.label_74 = QLabel(self.groupBoxConfigFan6)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(20, 120, 151, 21))
        self.label_74.setFont(font7)
        self.spinBoxMaxSpeedFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxMaxSpeedFan6.setObjectName(u"spinBoxMaxSpeedFan6")
        self.spinBoxMaxSpeedFan6.setGeometry(QRect(190, 120, 42, 21))
        self.spinBoxMaxSpeedFan6.setFont(font7)
        self.spinBoxMaxSpeedFan6.setMaximum(100)
        self.spinBoxMaxSpeedFan6.setSingleStep(1)
        self.spinBoxMaxSpeedFan6.setValue(100)
        self.label_75 = QLabel(self.groupBoxConfigFan6)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(240, 120, 101, 21))
        self.label_75.setFont(font7)
        self.label_76 = QLabel(self.groupBoxConfigFan6)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(330, 120, 111, 21))
        self.label_76.setFont(font7)
        self.spinBoxMaxTempFan6 = QSpinBox(self.groupBoxConfigFan6)
        self.spinBoxMaxTempFan6.setObjectName(u"spinBoxMaxTempFan6")
        self.spinBoxMaxTempFan6.setGeometry(QRect(280, 120, 42, 21))
        self.spinBoxMaxTempFan6.setFont(font7)
        self.spinBoxMaxTempFan6.setMaximum(100)
        self.spinBoxMaxTempFan6.setSingleStep(1)
        self.spinBoxMaxTempFan6.setValue(75)
        self.radioButtonCPUFan6 = QRadioButton(self.groupBoxConfigFan6)
        self.radioButtonCPUFan6.setObjectName(u"radioButtonCPUFan6")
        self.radioButtonCPUFan6.setGeometry(QRect(370, 20, 95, 20))
        self.radioButtonCPUFan6.setFont(font7)
        self.radioButtonCPUFan6.setChecked(True)
        self.radioButtonGPUFan6 = QRadioButton(self.groupBoxConfigFan6)
        self.radioButtonGPUFan6.setObjectName(u"radioButtonGPUFan6")
        self.radioButtonGPUFan6.setGeometry(QRect(370, 40, 95, 20))
        self.radioButtonGPUFan6.setFont(font7)
        self.tabWidget.addTab(self.tabFanConfig, "")
        self.tabRenameFans = QWidget()
        self.tabRenameFans.setObjectName(u"tabRenameFans")
        self.tabRenameFans.setEnabled(True)
        self.groupBoxFanNames = QGroupBox(self.tabRenameFans)
        self.groupBoxFanNames.setObjectName(u"groupBoxFanNames")
        self.groupBoxFanNames.setEnabled(True)
        self.groupBoxFanNames.setGeometry(QRect(20, 20, 621, 211))
        self.groupBoxFanNames.setFont(font4)
        self.label_77 = QLabel(self.groupBoxFanNames)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(20, 80, 51, 21))
        self.label_77.setFont(font1)
        self.lineEditFan5 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan5.setObjectName(u"lineEditFan5")
        self.lineEditFan5.setGeometry(QRect(380, 80, 201, 22))
        self.lineEditFan5.setFont(font4)
        self.label_147 = QLabel(self.groupBoxFanNames)
        self.label_147.setObjectName(u"label_147")
        self.label_147.setGeometry(QRect(320, 80, 51, 21))
        self.label_147.setFont(font1)
        self.lineEditFan4 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan4.setObjectName(u"lineEditFan4")
        self.lineEditFan4.setGeometry(QRect(380, 40, 201, 22))
        self.lineEditFan4.setFont(font4)
        self.label_6 = QLabel(self.groupBoxFanNames)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 40, 51, 21))
        self.label_6.setFont(font1)
        self.label_78 = QLabel(self.groupBoxFanNames)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(20, 120, 51, 21))
        self.label_78.setFont(font1)
        self.lineEditFan6 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan6.setObjectName(u"lineEditFan6")
        self.lineEditFan6.setGeometry(QRect(380, 120, 201, 22))
        self.lineEditFan6.setFont(font4)
        self.lineEditFan2 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan2.setObjectName(u"lineEditFan2")
        self.lineEditFan2.setGeometry(QRect(80, 80, 201, 22))
        self.lineEditFan2.setFont(font4)
        self.label_149 = QLabel(self.groupBoxFanNames)
        self.label_149.setObjectName(u"label_149")
        self.label_149.setGeometry(QRect(320, 120, 51, 21))
        self.label_149.setFont(font1)
        self.label_148 = QLabel(self.groupBoxFanNames)
        self.label_148.setObjectName(u"label_148")
        self.label_148.setGeometry(QRect(320, 40, 51, 21))
        self.label_148.setFont(font1)
        self.lineEditFan1 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan1.setObjectName(u"lineEditFan1")
        self.lineEditFan1.setGeometry(QRect(80, 40, 201, 22))
        self.lineEditFan1.setFont(font4)
        self.lineEditFan3 = QLineEdit(self.groupBoxFanNames)
        self.lineEditFan3.setObjectName(u"lineEditFan3")
        self.lineEditFan3.setGeometry(QRect(80, 120, 201, 22))
        self.lineEditFan3.setFont(font4)
        self.label_4 = QLabel(self.groupBoxFanNames)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 160, 281, 31))
        font10 = QFont()
        font10.setPointSize(10)
        font10.setItalic(True)
        self.label_4.setFont(font10)
        self.tabWidget.addTab(self.tabRenameFans, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1033, 22))
        MainWindow.setMenuBar(self.menuBar)
        QWidget.setTabOrder(self.comboBoxComPorts, self.comboBoxPolling)
        QWidget.setTabOrder(self.comboBoxPolling, self.horizontalSliderFan1)
        QWidget.setTabOrder(self.horizontalSliderFan1, self.horizontalSliderFan2)
        QWidget.setTabOrder(self.horizontalSliderFan2, self.horizontalSliderFan3)
        QWidget.setTabOrder(self.horizontalSliderFan3, self.horizontalSliderFan4)
        QWidget.setTabOrder(self.horizontalSliderFan4, self.horizontalSliderFan5)
        QWidget.setTabOrder(self.horizontalSliderFan5, self.horizontalSliderFan6)
        QWidget.setTabOrder(self.horizontalSliderFan6, self.pushButtonRemoveCPUSensor)
        QWidget.setTabOrder(self.pushButtonRemoveCPUSensor, self.pushButtonAddGPUSensor)
        QWidget.setTabOrder(self.pushButtonAddGPUSensor, self.pushButtonRemoveGPUSensor)
        QWidget.setTabOrder(self.pushButtonRemoveGPUSensor, self.spinBoxMinSpeedFan1)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan1, self.spinBoxStartIncreaseSpeedFan1)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan1, self.spinBoxIntermediateSpeedFan1)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan1, self.spinBoxIntermediateTempFan1)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan1, self.spinBoxMaxSpeedFan1)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan1, self.spinBoxMaxTempFan1)
        QWidget.setTabOrder(self.spinBoxMaxTempFan1, self.spinBoxMinSpeedFan2)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan2, self.spinBoxStartIncreaseSpeedFan2)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan2, self.spinBoxIntermediateSpeedFan2)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan2, self.spinBoxIntermediateTempFan2)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan2, self.spinBoxMaxSpeedFan2)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan2, self.spinBoxMaxTempFan2)
        QWidget.setTabOrder(self.spinBoxMaxTempFan2, self.spinBoxMinSpeedFan3)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan3, self.spinBoxStartIncreaseSpeedFan3)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan3, self.spinBoxIntermediateSpeedFan3)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan3, self.spinBoxIntermediateTempFan3)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan3, self.spinBoxMaxSpeedFan3)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan3, self.spinBoxMaxTempFan3)
        QWidget.setTabOrder(self.spinBoxMaxTempFan3, self.spinBoxMinSpeedFan4)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan4, self.spinBoxStartIncreaseSpeedFan4)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan4, self.spinBoxIntermediateSpeedFan4)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan4, self.spinBoxIntermediateTempFan4)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan4, self.spinBoxMaxSpeedFan4)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan4, self.spinBoxMaxTempFan4)
        QWidget.setTabOrder(self.spinBoxMaxTempFan4, self.spinBoxMinSpeedFan5)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan5, self.spinBoxStartIncreaseSpeedFan5)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan5, self.spinBoxIntermediateSpeedFan5)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan5, self.spinBoxIntermediateTempFan5)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan5, self.spinBoxMaxSpeedFan5)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan5, self.spinBoxMaxTempFan5)
        QWidget.setTabOrder(self.spinBoxMaxTempFan5, self.spinBoxMinSpeedFan6)
        QWidget.setTabOrder(self.spinBoxMinSpeedFan6, self.spinBoxStartIncreaseSpeedFan6)
        QWidget.setTabOrder(self.spinBoxStartIncreaseSpeedFan6, self.spinBoxIntermediateSpeedFan6)
        QWidget.setTabOrder(self.spinBoxIntermediateSpeedFan6, self.spinBoxIntermediateTempFan6)
        QWidget.setTabOrder(self.spinBoxIntermediateTempFan6, self.spinBoxMaxSpeedFan6)
        QWidget.setTabOrder(self.spinBoxMaxSpeedFan6, self.spinBoxMaxTempFan6)
        QWidget.setTabOrder(self.spinBoxMaxTempFan6, self.lineEditFan1)
        QWidget.setTabOrder(self.lineEditFan1, self.lineEditFan2)
        QWidget.setTabOrder(self.lineEditFan2, self.lineEditFan3)
        QWidget.setTabOrder(self.lineEditFan3, self.lineEditFan4)
        QWidget.setTabOrder(self.lineEditFan4, self.lineEditFan5)
        QWidget.setTabOrder(self.lineEditFan5, self.lineEditFan6)
        QWidget.setTabOrder(self.lineEditFan6, self.radioButtonGPUFan4)
        QWidget.setTabOrder(self.radioButtonGPUFan4, self.radioButtonCPUMax)
        QWidget.setTabOrder(self.radioButtonCPUMax, self.radioButtonCPUFan2)
        QWidget.setTabOrder(self.radioButtonCPUFan2, self.radioButtonCPUAverage)
        QWidget.setTabOrder(self.radioButtonCPUAverage, self.radioButtonGPUFan2)
        QWidget.setTabOrder(self.radioButtonGPUFan2, self.radioButtonAutomatic)
        QWidget.setTabOrder(self.radioButtonAutomatic, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.radioButtonCPUFan5)
        QWidget.setTabOrder(self.radioButtonCPUFan5, self.radioButtonGPUFan5)
        QWidget.setTabOrder(self.radioButtonGPUFan5, self.pushButtonAddCPUSensor)
        QWidget.setTabOrder(self.pushButtonAddCPUSensor, self.radioButtonGPUMax)
        QWidget.setTabOrder(self.radioButtonGPUMax, self.radioButtonCPUFan3)
        QWidget.setTabOrder(self.radioButtonCPUFan3, self.radioButtonCPUFan1)
        QWidget.setTabOrder(self.radioButtonCPUFan1, self.radioButtonGPUFan3)
        QWidget.setTabOrder(self.radioButtonGPUFan3, self.radioButtonGPUFan1)
        QWidget.setTabOrder(self.radioButtonGPUFan1, self.radioButtonCPUFan6)
        QWidget.setTabOrder(self.radioButtonCPUFan6, self.radioButtonGPUFan6)
        QWidget.setTabOrder(self.radioButtonGPUFan6, self.treeWidgetSelectedGPUSensors)
        QWidget.setTabOrder(self.treeWidgetSelectedGPUSensors, self.treeWidgetHWMonData)
        QWidget.setTabOrder(self.treeWidgetHWMonData, self.radioButtonCPUFan4)
        QWidget.setTabOrder(self.radioButtonCPUFan4, self.treeWidgetSelectedCPUSensors)
        QWidget.setTabOrder(self.treeWidgetSelectedCPUSensors, self.radioButtonGPUAverage)
        QWidget.setTabOrder(self.radioButtonGPUAverage, self.radioButtonManual)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Grid Control", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.groupBoxCurrentCPUTemp.setTitle(QCoreApplication.translate("MainWindow", u"Current CPU temp", None))
        self.label_192.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.groupBoxFanControl.setTitle(QCoreApplication.translate("MainWindow", u"Fan control", None))
        self.radioButtonManual.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.radioButtonAutomatic.setText(QCoreApplication.translate("MainWindow", u"Automatic", None))
        self.groupBoxFan1.setTitle(QCoreApplication.translate("MainWindow", u"Fan 1", None))
        self.label_152.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxFan2.setTitle(QCoreApplication.translate("MainWindow", u"Fan 2", None))
        self.label_153.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxFan3.setTitle(QCoreApplication.translate("MainWindow", u"Fan 3", None))
        self.label_154.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxFan4.setTitle(QCoreApplication.translate("MainWindow", u"Fan 4", None))
        self.label_158.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxFan6.setTitle(QCoreApplication.translate("MainWindow", u"Fan 6", None))
        self.label_159.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxFan5.setTitle(QCoreApplication.translate("MainWindow", u"Fan 5", None))
        self.label_160.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.groupBoxSimulateTemperatures.setTitle(QCoreApplication.translate("MainWindow", u"Simulate temperatures", None))
        self.checkBoxSimulateTemp.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.labelCPU.setText(QCoreApplication.translate("MainWindow", u"CPU Temp", None))
        self.labelGPU.setText(QCoreApplication.translate("MainWindow", u"GPU Temp", None))
        self.groupBoxCurrentFanStatus.setTitle(QCoreApplication.translate("MainWindow", u"Fan status", None))
        self.groupBoxCurrentFan1.setTitle(QCoreApplication.translate("MainWindow", u"Fan 1", None))
        self.labelStatusFan1.setText("")
        self.label_164.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan1.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_165.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.labelVFan1.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.groupBoxCurrentFan2.setTitle(QCoreApplication.translate("MainWindow", u"Fan 2", None))
        self.label_170.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan2.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.labelStatusFan2.setText("")
        self.labelVFan2.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_166.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.groupBoxCurrentFan3.setTitle(QCoreApplication.translate("MainWindow", u"Fan 3", None))
        self.label_174.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan3.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.labelStatusFan3.setText("")
        self.labelVFan3.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_167.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.groupBoxCurrentFan4.setTitle(QCoreApplication.translate("MainWindow", u"Fan 4", None))
        self.label_182.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan4.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.labelStatusFan4.setText("")
        self.labelVFan4.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_168.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.groupBoxCurrentFan5.setTitle(QCoreApplication.translate("MainWindow", u"Fan 5", None))
        self.label_186.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan5.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.labelStatusFan5.setText("")
        self.labelVFan5.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_171.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.groupBoxCurrentFan6.setTitle(QCoreApplication.translate("MainWindow", u"Fan 6", None))
        self.label_191.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.labelRPMFan6.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.labelStatusFan6.setText("")
        self.labelVFan6.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
        self.label_172.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.groupBoxHWMon.setTitle(QCoreApplication.translate("MainWindow", u"Libre Hardware Monitor", None))
        self.label_151.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.labelHWMonStatus.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.groupBoxGridSetup.setTitle(QCoreApplication.translate("MainWindow", u"Grid V2", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Serial port", None))
        self.comboBoxComPorts.setItemText(0, QCoreApplication.translate("MainWindow", u"<Select port>", None))

        self.comboBoxComPorts.setCurrentText(QCoreApplication.translate("MainWindow", u"<Select port>", None))
        self.pushButtonRestart.setText(QCoreApplication.translate("MainWindow", u"Restart Communication", None))
        self.label_204.setText(QCoreApplication.translate("MainWindow", u"Polling interval", None))
        self.comboBoxPolling.setItemText(0, QCoreApplication.translate("MainWindow", u"100", None))
        self.comboBoxPolling.setItemText(1, QCoreApplication.translate("MainWindow", u"500", None))
        self.comboBoxPolling.setItemText(2, QCoreApplication.translate("MainWindow", u"1000", None))
        self.comboBoxPolling.setItemText(3, QCoreApplication.translate("MainWindow", u"2000", None))
        self.comboBoxPolling.setItemText(4, QCoreApplication.translate("MainWindow", u"5000", None))

        self.label_205.setText(QCoreApplication.translate("MainWindow", u"msec", None))
        self.groupBoxCurrentGPUTemp.setTitle(QCoreApplication.translate("MainWindow", u"Current GPU temp", None))
        self.label_203.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.labelGridImage.setText("")
        self.groupBoxGridSetup_2.setTitle(QCoreApplication.translate("MainWindow", u"Polling", None))
        self.label_155.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.labelPollingStatus.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.checkBoxStartMinimized.setText(QCoreApplication.translate("MainWindow", u"Start minimized", None))
        self.checkBoxMinimizeToTray.setText(QCoreApplication.translate("MainWindow", u"Minimize to tray", None))
        self.checkBoxStartSilently.setText(QCoreApplication.translate("MainWindow", u"Start silently", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QCoreApplication.translate("MainWindow", u"General", None))
        self.pushButtonRemoveGPUSensor.setText(QCoreApplication.translate("MainWindow", u"<- Remove", None))
        self.groupBoxCPUSensors.setTitle(QCoreApplication.translate("MainWindow", u"Value to use", None))
        self.radioButtonCPUMax.setText(QCoreApplication.translate("MainWindow", u"Use Max value", None))
        self.radioButtonCPUAverage.setText(QCoreApplication.translate("MainWindow", u"Use Average value", None))
        self.pushButtonAddCPUSensor.setText(QCoreApplication.translate("MainWindow", u"Add ->", None))
        self.pushButtonAddGPUSensor.setText(QCoreApplication.translate("MainWindow", u"Add ->", None))
        self.groupBoxGPUSensors.setTitle(QCoreApplication.translate("MainWindow", u"Value to use", None))
        self.radioButtonGPUMax.setText(QCoreApplication.translate("MainWindow", u"Use Max value", None))
        self.radioButtonGPUAverage.setText(QCoreApplication.translate("MainWindow", u"Use Average value", None))
        self.pushButtonRemoveCPUSensor.setText(QCoreApplication.translate("MainWindow", u"<- Remove", None))
        self.groupBoxAvailableSensors.setTitle(QCoreApplication.translate("MainWindow", u"Available temperature sensors", None))
        self.groupBoxSelectedCPUSensors.setTitle(QCoreApplication.translate("MainWindow", u"Selected CPU sensor(s)", None))
        self.groupBoxSelectedGPUSensors.setTitle(QCoreApplication.translate("MainWindow", u"Selected GPU sensor(s)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Click on \"Restart Communication\" on \"General\" tab to apply changes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSensorConfig), QCoreApplication.translate("MainWindow", u"Sensor Config", None))
        self.groupBoxConfigFan1.setTitle(QCoreApplication.translate("MainWindow", u"Fan 1", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan1.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan1.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.groupBoxConfigFan2.setTitle(QCoreApplication.translate("MainWindow", u"Fan 2", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan2.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan2.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.groupBoxConfigFan3.setTitle(QCoreApplication.translate("MainWindow", u"Fan 3", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan3.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan3.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.groupBoxConfigFan4.setTitle(QCoreApplication.translate("MainWindow", u"Fan 4", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan4.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan4.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.groupBoxConfigFan5.setTitle(QCoreApplication.translate("MainWindow", u"Fan 5", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan5.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan5.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.groupBoxConfigFan6.setTitle(QCoreApplication.translate("MainWindow", u"Fan 6", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Minimum fan speed", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Start increase fan speed at ", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Intermediate fan speed ", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"Maximum fan speed ", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"%  at", None))
        self.label_76.setText(QCoreApplication.translate("MainWindow", u"\u00b0C or higher", None))
        self.radioButtonCPUFan6.setText(QCoreApplication.translate("MainWindow", u"CPU temp", None))
        self.radioButtonGPUFan6.setText(QCoreApplication.translate("MainWindow", u"GPU temp", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFanConfig), QCoreApplication.translate("MainWindow", u"Fan Config", None))
        self.groupBoxFanNames.setTitle(QCoreApplication.translate("MainWindow", u"Fan labels", None))
        self.label_77.setText(QCoreApplication.translate("MainWindow", u"Fan 2", None))
        self.lineEditFan5.setText(QCoreApplication.translate("MainWindow", u"Fan 5", None))
        self.label_147.setText(QCoreApplication.translate("MainWindow", u"Fan 5", None))
        self.lineEditFan4.setText(QCoreApplication.translate("MainWindow", u"Fan 4", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Fan 1", None))
        self.label_78.setText(QCoreApplication.translate("MainWindow", u"Fan 3", None))
        self.lineEditFan6.setText(QCoreApplication.translate("MainWindow", u"Fan 6", None))
        self.lineEditFan2.setText(QCoreApplication.translate("MainWindow", u"Fan 2", None))
        self.label_149.setText(QCoreApplication.translate("MainWindow", u"Fan 6", None))
        self.label_148.setText(QCoreApplication.translate("MainWindow", u"Fan 4", None))
        self.lineEditFan1.setText(QCoreApplication.translate("MainWindow", u"Fan 1", None))
        self.lineEditFan3.setText(QCoreApplication.translate("MainWindow", u"Fan 3", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Restart application to apply changes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRenameFans), QCoreApplication.translate("MainWindow", u"Rename Fans", None))
    # retranslateUi

